function isLetter(charCode) {
	console.log(charCode);
	switch (charCode) {
		case 65: return true;
		case 66: return true;
		case 67: return true;
		case 68: return true;
		case 69: return true;
		case 70: return true;
		case 71: return true;
		case 72: return true;
		case 73: return true;
		case 74: return true;
		case 75: return true;
		case 76: return true;
		case 77: return true;
		case 78: return true;
		case 79: return true;
		case 80: return true;
		case 81: return true;
		case 82: return true;
		case 83: return true;
		case 84: return true;
		case 85: return true;
		case 86: return true;
		case 87: return true;
		case 88: return true;
		case 89: return true;
		case 90: return true;
		case 97: return true;
		case 98: return true;
		case 99: return true;
		case 100: return true;
		case 101: return true;
		case 102: return true;
		case 103: return true;
		case 104: return true;
		case 105: return true;
		case 106: return true;
		case 107: return true;
		case 108: return true;
		case 109: return true;
		case 110: return true;
		case 111: return true;
		case 112: return true;
		case 113: return true;
		case 114: return true;
		case 115: return true;
		case 116: return true;
		case 117: return true;
		case 118: return true;
		case 119: return true;
		case 120: return true;
		case 121: return true;
		case 122: return true;
		default: return false;
	}
}

module.exports = isLetter;